// All user-facing copy lives here so it can be translated later.
export const strings = {
  appName: 'Aether',
  common: {
    cancel: 'Cancel',
    save: 'Save',
    saved: 'Saved',
    delete: 'Delete',
    close: 'Close',
    copy: 'Copy',
    copied: 'Copied',
    download: 'Download',
    rename: 'Rename',
    edit: 'Edit',
    back: 'Back',
    create: 'Create',
    remove: 'Remove',
    loading: 'Loading…',
  },
  sidebar: {
    newChat: 'New chat',
    search: 'Search chats',
    projects: 'Projects',
    settings: 'Settings',
    recents: 'Recents',
    pinned: 'Pinned',
    today: 'Today',
    yesterday: 'Yesterday',
    week: 'Previous 7 days',
    older: 'Older',
    noChats: 'No conversations yet.',
    noResults: 'No chats match your search.',
    openMenu: 'Open sidebar',
    closeMenu: 'Close sidebar',
    collapse: 'Collapse sidebar',
    chatActions: 'Chat actions',
    pin: 'Pin',
    unpin: 'Unpin',
    confirmDelete: 'Delete this conversation? This cannot be undone.',
  },
  chat: {
    untitled: 'New chat',
    placeholder: 'How can I help you today?',
    replyPlaceholder: 'Reply to Aether…',
    send: 'Send message',
    stop: 'Stop generating',
    attach: 'Attach files',
    retry: 'Retry',
    regenerate: 'Regenerate response',
    editMessage: 'Edit message',
    saveAndSend: 'Save & send',
    copyMessage: 'Copy message',
    thinking: 'Thinking',
    thoughtProcess: 'Thought process',
    stopped: 'Generation stopped.',
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    emptyHint: 'Ask anything. Aether streams from the model you configure.',
    notConfigured: 'Connect a model to start chatting.',
    openSettings: 'Open settings',
    inProject: 'In project',
    showArtifacts: 'Show artifacts',
    hideArtifacts: 'Hide artifacts',
    extracting: 'Reading file…',
    disclaimer: 'Responses come from your configured model and may be inaccurate.',
    suggestions: [
      'Write a landing page in a single HTML file',
      'Explain a concept like I am new to it',
      'Draft a project brief in markdown',
      'Review this code for bugs',
    ],
  },
  errors: {
    auth: 'Authentication failed (401). Check your API key in Settings.',
    forbidden: 'Access denied (403). Your key may not have access to this model.',
    model: 'The model was not found. Check the model id in Settings.',
    notFound: 'Endpoint not found (404). Check the Base URL — it usually ends in /v1.',
    rateLimit: 'Rate limited (429). Wait a moment and try again.',
    server: 'The server returned an error',
    cors: 'The request was blocked — most likely CORS, or the server is unreachable. Turn on “Call via proxy” in Settings, or check that the server is running.',
    corsNative:
      'The request was blocked — the server may not allow app requests (CORS) or is unreachable. Use a provider that supports browser access (OpenAI, OpenRouter, Groq) or check the server address.',
    network: 'Network error — you appear to be offline or the server is unreachable.',
    proxyUnavailable: 'The proxy is only available when the app is served by `npm run dev`, `npm run preview` or `npm run serve`.',
    config: 'Set a Base URL and model in Settings first.',
    emptyResponse: 'The model returned an empty response.',
    fileTooLarge: 'File is too large (max 20 MB).',
    fileUnsupported: 'Unsupported file type.',
    fileRead: 'Could not read file.',
  },
  settings: {
    title: 'Settings',
    backend: 'Model backend',
    backendHint: 'Any OpenAI-compatible server. Everything is stored only on this device.',
    presets: 'Quick presets',
    baseUrl: 'Base URL',
    apiKey: 'API key',
    apiKeyHint: 'Optional for local servers like Ollama or LM Studio.',
    showKey: 'Show key',
    hideKey: 'Hide key',
    model: 'Model',
    modelHint: 'For example gpt-4o-mini, llama-3.3-70b-versatile, or llama3.2.',
    loadModels: 'Load models',
    modelsLoaded: (n: number) => `${n} models available`,
    useProxy: 'Call via proxy',
    useProxyHint:
      'Routes requests through the Aether server to avoid browser CORS errors. Requires running via npm run dev / preview / serve.',
    useProxyNative: 'Not available in the iOS app — requests go directly to the server.',
    thinkingEffort: 'Thinking effort',
    thinkingEffortHint:
      'Auto sends nothing. Low / Medium / High send reasoning_effort (OpenRouter: reasoning.effort) — only for reasoning models.',
    vision: 'Send images to the model',
    visionHint: 'Attach images as image_url parts (vision models). Falls back to text automatically if rejected.',
    instructions: 'Custom instructions',
    instructionsHint: 'Applied to every conversation. Project instructions are added on top.',
    instructionsPlaceholder: 'e.g. Be concise. I prefer TypeScript examples.',
    test: 'Test connection',
    testing: 'Testing…',
    testOkModels: (n: number) => `Connected — ${n} models listed.`,
    testOkChat: 'Connected — the model replied.',
    data: 'Data',
    dataHint: 'Conversations, projects and files are stored in this browser (IndexedDB).',
    clearAll: 'Delete all conversations',
    confirmClearAll: 'Delete every conversation and message? Projects are kept.',
  },
  modelMenu: {
    button: 'Choose model',
    noModel: 'Choose a model',
    search: 'Search or type a model id',
    recent: 'Recent',
    available: 'Available',
    refresh: 'Refresh model list',
    loading: 'Loading models…',
    useCustom: (id: string) => `Use “${id}”`,
    empty: 'No models listed. Type a model id above.',
    effort: 'Thinking',
    efforts: { auto: 'Auto', low: 'Low', medium: 'Medium', high: 'High' },
    manage: 'Model settings',
  },
  projects: {
    title: 'Projects',
    subtitle: 'Group chats with shared instructions and knowledge files.',
    new: 'New project',
    name: 'Project name',
    namePlaceholder: 'e.g. Thesis research',
    instructions: 'Project instructions',
    instructionsPlaceholder: 'How should Aether behave in this project?',
    empty: 'No projects yet. Create one to share instructions and files across chats.',
    files: 'Knowledge',
    filesHint: 'TXT, MD, JSON, CSV, PDF and images. Extracts are added to the system prompt.',
    upload: 'Upload files',
    noFiles: 'No files yet.',
    chats: 'Chats in this project',
    noChats: 'No chats yet.',
    newChat: 'New chat in project',
    confirmDelete: 'Delete this project and its files? Chats are kept but detached.',
    deleteProject: 'Delete project',
    deleteFile: 'Delete file',
    fileCount: (n: number) => `${n} file${n === 1 ? '' : 's'}`,
    chatCount: (n: number) => `${n} chat${n === 1 ? '' : 's'}`,
    textChars: (n: number) => `${n.toLocaleString()} chars extracted`,
    imageFile: 'Image',
    none: 'No project',
  },
  artifacts: {
    preview: 'Preview',
    code: 'Code',
    generating: 'Generating…',
    version: (v: number, total: number) => `v${v} of ${total}`,
    previousVersion: 'Previous version',
    nextVersion: 'Next version',
    open: 'Open artifact',
    close: 'Close artifact',
    clickToOpen: 'Click to open',
    defaultTitle: { html: 'Web page', markdown: 'Document', code: 'Code' },
    typeLabel: { html: 'HTML', markdown: 'Document', code: 'Code' },
    iframeTitle: 'Artifact preview',
  },
} as const;
